// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

namespace omni.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221015072413_Classes")]
    partial class Classes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("omni.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 70, 58, 152, 235, 187, 185, 88, 39, 56, 0, 135, 161, 30, 32, 218, 190, 172, 131, 26, 29, 91, 51, 24, 21, 124, 115, 211, 210, 251, 19, 136, 119, 127, 141, 172, 79, 69, 29, 254, 143, 177, 58, 103, 95, 150, 81, 40, 57, 51, 64, 178, 3, 76, 88, 73, 201, 151, 11, 237, 128, 253, 236, 187, 206 },
                            PasswordSalt = new byte[] { 161, 20, 135, 244, 153, 235, 92, 161, 70, 105, 86, 241, 65, 105, 2, 222, 55, 93, 146, 117, 172, 127, 185, 244, 40, 27, 64, 255, 36, 123, 134, 102, 192, 60, 6, 58, 34, 145, 40, 187, 199, 23, 43, 51, 250, 119, 210, 171, 37, 153, 156, 156, 159, 209, 154, 73, 163, 154, 221, 212, 227, 200, 41, 218, 121, 123, 171, 247, 200, 203, 32, 7, 10, 156, 35, 219, 99, 129, 192, 136, 159, 85, 6, 72, 240, 242, 113, 114, 235, 19, 205, 218, 251, 48, 58, 142, 83, 186, 28, 28, 120, 47, 159, 13, 0, 195, 248, 176, 105, 124, 154, 138, 115, 228, 177, 236, 232, 149, 34, 162, 140, 219, 86, 144, 188, 166, 24, 244 },
                            Username = "UsuarioAdmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
