// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

namespace omni.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221015074203_Denuncia")]
    partial class Denuncia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("omni.Models.Apontamentos", b =>
                {
                    b.Property<int>("IdApontamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoApontamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDenuncia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MomentoApontamento")
                        .HasColumnType("datetime2");

                    b.HasKey("IdApontamento");

                    b.ToTable("Apontamentos");
                });

            modelBuilder.Entity("omni.Models.Cidadao", b =>
                {
                    b.Property<int>("IdCidadao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontuacaoCidadao")
                        .HasColumnType("int");

                    b.Property<string>("Secao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloEleitor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaEleitoral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCidadao");

                    b.ToTable("Cidadaos");
                });

            modelBuilder.Entity("omni.Models.Denuncia", b =>
                {
                    b.Property<int>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataDenuncia")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCidadao")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDenuncia")
                        .HasColumnType("int");

                    b.Property<string>("LocalDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontosPrioridade")
                        .HasColumnType("int");

                    b.HasKey("IdDenuncia");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("omni.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 226, 20, 27, 224, 36, 59, 53, 211, 181, 139, 153, 202, 72, 25, 53, 215, 173, 186, 32, 244, 88, 121, 202, 41, 166, 125, 44, 221, 54, 76, 144, 16, 172, 3, 57, 88, 48, 71, 149, 218, 39, 127, 196, 81, 166, 104, 148, 123, 110, 34, 229, 248, 7, 75, 127, 113, 22, 51, 11, 10, 112, 32, 24, 1 },
                            PasswordSalt = new byte[] { 131, 109, 75, 157, 174, 182, 190, 5, 41, 65, 208, 146, 231, 166, 131, 59, 46, 5, 111, 197, 140, 221, 101, 83, 124, 68, 220, 185, 203, 166, 89, 190, 120, 105, 135, 136, 31, 137, 1, 206, 105, 246, 235, 100, 59, 68, 126, 136, 15, 117, 161, 137, 161, 140, 187, 15, 113, 20, 222, 47, 194, 162, 75, 24, 89, 20, 0, 111, 51, 237, 223, 253, 225, 152, 221, 172, 165, 159, 113, 159, 120, 95, 241, 247, 240, 75, 40, 167, 109, 180, 60, 17, 150, 127, 25, 102, 118, 49, 110, 77, 70, 65, 168, 242, 13, 88, 82, 112, 229, 254, 84, 193, 201, 35, 106, 131, 218, 164, 195, 60, 39, 137, 46, 250, 95, 210, 113, 7 },
                            Username = "UsuarioAdmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
