// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

namespace omni.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221015072755_Classesss")]
    partial class Classesss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("omni.Models.Cidadao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontuacaoCidadao")
                        .HasColumnType("int");

                    b.Property<string>("Secao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloEleitor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaEleitoral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cidadaos");
                });

            modelBuilder.Entity("omni.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 177, 150, 103, 135, 220, 132, 115, 13, 197, 197, 178, 56, 108, 12, 41, 228, 104, 168, 96, 44, 135, 56, 111, 188, 118, 213, 205, 61, 54, 49, 17, 181, 31, 215, 32, 205, 113, 139, 63, 108, 243, 78, 200, 176, 104, 247, 161, 121, 162, 62, 201, 93, 19, 101, 109, 23, 34, 161, 140, 245, 121, 31, 219, 231 },
                            PasswordSalt = new byte[] { 153, 24, 112, 82, 191, 67, 199, 88, 126, 98, 226, 94, 191, 92, 20, 100, 47, 53, 194, 161, 164, 238, 80, 86, 37, 39, 113, 249, 8, 60, 177, 221, 203, 143, 186, 90, 95, 153, 109, 227, 132, 54, 125, 247, 23, 181, 16, 106, 207, 101, 254, 77, 73, 23, 73, 142, 170, 174, 37, 59, 79, 230, 205, 109, 20, 109, 106, 247, 133, 202, 35, 35, 177, 32, 185, 182, 28, 255, 236, 59, 96, 125, 6, 205, 46, 67, 125, 63, 203, 230, 160, 19, 121, 179, 0, 180, 66, 169, 17, 70, 228, 220, 62, 45, 100, 19, 26, 32, 218, 143, 177, 20, 247, 14, 243, 145, 137, 98, 248, 203, 217, 212, 62, 245, 50, 160, 76, 2 },
                            Username = "UsuarioAdmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
