// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

namespace omni.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("omni.Models.Apontamentos", b =>
                {
                    b.Property<int>("IdApontamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoApontamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDenuncia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MomentoApontamento")
                        .HasColumnType("datetime2");

                    b.HasKey("IdApontamento");

                    b.ToTable("Apontamentos");
                });

            modelBuilder.Entity("omni.Models.Cidadao", b =>
                {
                    b.Property<int>("IdCidadao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontuacaoCidadao")
                        .HasColumnType("int");

                    b.Property<string>("Secao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloEleitor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaEleitoral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCidadao");

                    b.ToTable("Cidadaos");
                });

            modelBuilder.Entity("omni.Models.Denuncia", b =>
                {
                    b.Property<int>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataDenuncia")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCidadao")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDenuncia")
                        .HasColumnType("int");

                    b.Property<string>("LocalDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontosPrioridade")
                        .HasColumnType("int");

                    b.HasKey("IdDenuncia");

                    b.HasAlternateKey("IdCidadao");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("omni.Models.FotoCidadao", b =>
                {
                    b.Property<int>("IdCidadao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("VbFotoCidadao")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdCidadao");

                    b.ToTable("FotoCidadaos");
                });

            modelBuilder.Entity("omni.Models.ImagemDenuncia", b =>
                {
                    b.Property<int>("IdImagemDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDenuncia")
                        .HasColumnType("int");

                    b.Property<byte[]>("VbImagemDenuncia")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdImagemDenuncia");

                    b.ToTable("ImagemDenuncias");
                });

            modelBuilder.Entity("omni.Models.ImagemPublicacao", b =>
                {
                    b.Property<int>("IdPublicacaoImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPublicacao")
                        .HasColumnType("int");

                    b.Property<byte[]>("VbPublicacaoImagem")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdPublicacaoImagem");

                    b.ToTable("ImagemPublicacaos");
                });

            modelBuilder.Entity("omni.Models.Publicacoes", b =>
                {
                    b.Property<int>("IdPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataFimExibicao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioExibicao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoPublicacao")
                        .HasColumnType("int");

                    b.Property<string>("LinkPublicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadePublicacao")
                        .HasColumnType("int");

                    b.Property<int>("SensibilidadePublicacao")
                        .HasColumnType("int");

                    b.Property<string>("TextoPublicacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPublicacao");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("omni.Models.StatusDenuncia", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusDenuncias");
                });

            modelBuilder.Entity("omni.Models.TipoPublicacao", b =>
                {
                    b.Property<int>("IdTipoPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoTipoPublicacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoPublicacao");

                    b.ToTable("TipoPublicacaos");
                });

            modelBuilder.Entity("omni.Models.TiposDenuncia", b =>
                {
                    b.Property<int>("IdTipoDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoTipoDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontuacaoTipoDenuncia")
                        .HasColumnType("int");

                    b.HasKey("IdTipoDenuncia");

                    b.ToTable("TiposDenuncias");
                });

            modelBuilder.Entity("omni.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 102, 192, 119, 176, 27, 137, 242, 153, 173, 167, 99, 220, 247, 55, 93, 85, 133, 99, 127, 63, 219, 107, 105, 173, 190, 47, 65, 77, 150, 152, 193, 229, 191, 93, 11, 204, 71, 168, 32, 184, 176, 32, 123, 185, 79, 109, 165, 157, 118, 106, 47, 99, 134, 165, 97, 119, 134, 6, 207, 2, 74, 115, 147, 186 },
                            PasswordSalt = new byte[] { 36, 26, 222, 128, 126, 231, 6, 105, 65, 157, 193, 216, 253, 11, 37, 29, 163, 110, 159, 161, 149, 139, 100, 176, 127, 148, 92, 165, 152, 9, 100, 104, 189, 62, 102, 223, 146, 193, 96, 7, 129, 58, 3, 103, 148, 88, 136, 244, 88, 13, 142, 60, 157, 13, 2, 134, 175, 122, 135, 198, 114, 196, 161, 84, 189, 102, 147, 205, 22, 135, 67, 140, 100, 142, 137, 221, 111, 230, 138, 102, 104, 69, 88, 174, 191, 204, 49, 217, 96, 90, 5, 76, 158, 132, 230, 251, 76, 49, 81, 93, 73, 32, 20, 85, 247, 127, 191, 140, 30, 78, 203, 53, 7, 2, 195, 141, 159, 53, 31, 124, 66, 6, 30, 153, 31, 220, 186, 148 },
                            Username = "UsuarioAdmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
